language: python
python:
  - "3.8"

install:
  - pip install numpy
  - pip install opencv-contrib-python
dist: xenial
services:
  - xvfb

script: python eyeloop/run_eyeloop.py --video 'examples/optokinetic-reflex/Wild-type.avi'
